steps:
  # Install
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        apt update -q
        apt install -q -y make
  - name: 'node:12'
    entrypoint: bash
    args:
      - '-c'
      - |
        apt update -q
        apt install -q -y make
        npm install -g firebase-tools
        make app
