steps:
  # Install
  - name: 'node:14.7.0'
    entrypoint: npm
    args: ['install']

  # Install
  - name: 'node:14.7.0'
    entrypoint: npm
    args: ['install', 'firebase-tools']

  # Add Config
  - name: 'node:14.7.0'
    entrypoint: npm
    args: ['run', 'config']

  # Build
  - name: 'node:14.7.0'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy']
