steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Install firebase tools
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', 'firebase-tools']

  # Add Config
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'config']

  # Build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy']
